#** La lista nodes contiene la mayoría de los países del mundo **#
nodes = [
    "Afghanistan",
    "Angola",
    "Albania",
    "United Arab Emirates",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Burundi",
    "Belgium",
    "Benin",
    "Burkina Faso",
    "Bangladesh",
    "Bulgaria",
    "Bosnia and Herzegovina",
    "Belarus",
    "Belize",
    "Bolivia",
    "Brazil",
    "Brunei Darussalam",
    "Bhutan",
    "Botswana",
    "Central African Republic",
    "Canada",
    "Switzerland",
    "China",
    "Côte d'Ivoire",
    "Cameroon",
    "Democratic Republic of the Congo",
    "Republic of Congo",
    "Colombia",
    "Costa Rica",
    "Cuba",
    "Czech Republic",
    "Germany",
    "Djibouti",
    "Denmark",
    "Dominican Republic",
    "Algeria",
    "Ecuador",
    "Egypt",
    "Eritrea",
    "Estonia",
    "Ethiopia",
    "Finland",
    "Gabon",
    "United Kingdom",
    "Georgia",
    "Ghana",
    "Guinea",
    "Gambia",
    "Guinea-Bissau",
    "Equatorial Guinea",
    "Greece",
    "Greenland",
    "Guatemala",
    "Guyana",
    "Honduras",
    "Croatia",
    "Haiti",
    "Hungary",
    "Indonesia",
    "India",
    "Ireland",
    "Iran",
    "Iraq",
    "Iceland",
    "Israel",
    "Italy",
    "Jamaica",
    "Jordan",
    "Japan",
    "Kazakhstan",
    "Kenya",
    "Kyrgyzstan",
    "Cambodia",
    "South Korea",
    "Kuwait",
    "Lebanon",
    "Liberia",
    "Libya",
    "Sri Lanka",
    "Lesotho",
    "Lithuania",
    "Luxembourg",
    "Latvia",
    "Morocco",
    "Moldova",
    "Madagascar",
    "Mexico",
    "North Macedonia",
    "Mali",
    "Myanmar",
    "Montenegro",
    "Mongolia",
    "Mozambique",
    "Mauritania",
    "Malawi",
    "Malaysia",
    "Namibia",
    "Niger",
    "Nigeria",
    "Nicaragua",
    "Norway",
    "Nepal",
    "Oman",
    "Pakistan",
    "Panama",
    "Peru",
    "Philippines",
    "Papua New Guinea",
    "Poland",
    "North Korea",
    "Paraguay",
    "Palestine",
    "Qatar",
    "Romania",
    "Rwanda",
    "Western Sahara",
    "Saudi Arabia",
    "Sudan",
    "South Sudan",
    "Senegal",
    "Sierra Leone",
    "El Salvador",
    "Serbia",
    "Suriname",
    "Slovakia",
    "Slovenia",
    "Sweden",
    "Swaziland",
    "Syria",
    "Chad",
    "Togo",
    "Thailand",
    "Tajikistan",
    "Turkmenistan",
    "Timor-Leste",
    "Tunisia",
    "Turkey",
    "Taiwan",
    "Tanzania",
    "Uganda",
    "Ukraine",
    "Uruguay",
    "Uzbekistan",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe",
    "Somalia",
    "Kosovo",
    "South Africa",
    "New Zealand",
    "Chile",
    "Netherlands",
    "Portugal",
    "Russian Federation",
    "Spain",
    "France",
    "United States",
    "French Guiana",
    "Aruba",
    "Anguilla",
    "American Samoa",
    "Antigua and Barbuda",
    "Bahrain",
    "Bahamas",
    "Saint-Barthélemy",
    "Bermuda",
    "Barbados",
    "Comoros",
    "Cape Verde",
    "Curaçao",
    "Cayman Islands",
    "Cyprus",
    "Dominica",
    "Falkland Islands",
    "Faeroe Islands",
    "Federated States of Micronesia",
    "Grenada",
    "Guam",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Maldives",
    "Marshall Islands",
    "Malta",
    "Northern Mariana Islands",
    "Montserrat",
    "Mauritius",
    "New Caledonia",
    "Nauru",
    "Palau",
    "Puerto Rico",
    "Liechtenstein",
    "Saint Barthélemy",
    "Singapore",
    "Saint Vincent and the Grenadines",
    "Saint Martin",
    "Laos",
    "Réunion",
    "Monaco",
    "Netherlands Antilles",
    "Andorra",
    "Samoa",
    "Eswatini",
    "Martinique",
    "San Marino",
    "Vatican City",
    "Mayotte"
]
#** La distancias son aproximadas y no necesariamente representan la distancia real entre los países. **#
distancias_reales = {
    ('Afghanistan', 'China'): 5000,
    ('Afghanistan', 'Iran'): 921,
    ('Afghanistan', 'Pakistan'): 560,
    ('Afghanistan', 'Tajikistan'): 120,
    ('Afghanistan', 'Turkmenistan'): 744,
    ('Afghanistan', 'Uzbekistan'): 137,
    ('Angola', 'Democratic Republic of the Congo'): 400,
    ('Angola', 'Namibia'): 1376,
    ('Angola', 'Zambia'): 1050,
    ('Angola', 'Republic of Congo'): 250,
    ('United Arab Emirates', 'Oman'): 450,
    ('United Arab Emirates', 'Saudi Arabia'): 900,
    ('Argentina', 'Bolivia'): 2240,
    ('Argentina', 'Brazil'): 2900,
    ('Argentina', 'Chile'): 1400,
    ('Argentina', 'Paraguay'): 1300,
    ('Argentina', 'Uruguay'): 200,
    ('Argentina', 'Falkland Islands'): 1400,
    ('Armenia', 'Azerbaijan'): 460,
    ('Armenia', 'Georgia'): 280,
    ('Armenia', 'Iran'): 790,
    ('Armenia', 'Turkey'): 970,
    ('Australia', 'Papua New Guinea'): 3360,
    ('Australia', 'Indonesia'): 5220,
    ('Australia', 'New Zealand'): 2320,
    ('Austria', 'Czech Republic'): 250,
    ('Austria', 'Germany'): 680,
    ('Austria', 'Hungary'): 240,
    ('Austria', 'Italy'): 1130,
    ('Austria', 'Liechtenstein'): 600,
    ('Austria', 'Slovakia'): 80,
    ('Austria', 'Slovenia'): 380,
    ('Austria', 'Switzerland'): 750,
    ('Azerbaijan', 'Armenia'): 460,
    ('Azerbaijan', 'Georgia'): 450,
    ('Azerbaijan', 'Iran'): 530,
    ('Azerbaijan', 'Russian Federation'): 2500,
    ('Azerbaijan', 'Turkey'): 1600,
    ('Burundi', 'Democratic Republic of the Congo'): 200,
    ('Burundi', 'Rwanda'): 120,
    ('Burundi', 'Tanzania'): 800,
    ('Burundi', 'Uganda'): 900,
    ('Belgium', 'France'): 320,
    ('Belgium', 'Germany'): 770,
    ('Belgium', 'Luxembourg'): 190,
    ('Belgium', 'Netherlands'): 210,
    ('Burkina Faso', 'Benin'): 940,
    ('Burkina Faso', "Côte d'Ivoire"): 610,
    ('Burkina Faso', 'Ghana'): 760,
    ('Burkina Faso', 'Mali'): 920,
    ('Burkina Faso', 'Niger'): 420,
    ('Burkina Faso', 'Togo'): 870,
    ('Bangladesh', 'India'): 1420,
    ('Bangladesh', 'Myanmar'): 960,
    ('Bulgaria', 'Greece'): 800,
    ('Bulgaria', 'North Macedonia'): 240,
    ('Bulgaria', 'Romania'): 360,
    ('Bulgaria', 'Serbia'): 400,
    ('Bulgaria', 'Turkey'): 960,
    ('Bosnia and Herzegovina', 'Croatia'): 400,
    ('Bosnia and Herzegovina', 'Montenegro'): 230,
    ('Bosnia and Herzegovina', 'Serbia'): 290,
    ('Belarus', 'Latvia'): 170,
    ('Belarus', 'Lithuania'): 180,
    ('Belarus', 'Poland'): 250,
    ('Belarus', 'Russian Federation'): 700,
    ('Belarus', 'Ukraine'): 470,
    ('Belize', 'Guatemala'): 92,
    ('Belize', 'Mexico'): 277,
    ('Bolivia', 'Argentina'): 1881,
    ('Bolivia', 'Brazil'): 3000,
    ('Bolivia', 'Chile'): 1200,
    ('Bolivia', 'Paraguay'): 850,
    ('Bolivia', 'Peru'): 1070,
    ('Brazil', 'Argentina'): 2900,
    ('Brazil', 'Bolivia'): 3000,
    ('Brazil', 'Colombia'): 2500,
    ('Brazil', 'Guyana'): 1600,
    ('Brazil', 'Paraguay'): 1300,
    ('Brazil', 'Peru'): 2600,
    ('Brazil', 'Suriname'): 2000,
    ('Brazil', 'Uruguay'): 2100,
    ('Brazil', 'French Guiana'): 2000,
    ('Uruguay', 'Argentina'): 200,
    ('Uruguay', 'Brazil'): 2100,
    ('Brazil', 'Venezuela'): 2800,
    ('Brunei Darussalam', 'Malaysia'): 160,
    ('Brunei Darussalam', 'Philippines'): 1200,
    ('Bhutan', 'China'): 470,
    ('Bhutan', 'India'): 180,
    ('Botswana', 'Namibia'): 1100,
    ('Botswana', 'South Africa'): 960,
    ('Botswana', 'Zimbabwe'): 840,
    ('Botswana', 'Zambia'): 700,
    ('Central African Republic', 'Cameroon'): 800,
    ('Central African Republic', 'Chad'): 1100,
    ('Central African Republic', 'Democratic Republic of the Congo'): 1400,
    ('Central African Republic', 'Republic of Congo'): 1200,
    ('Central African Republic', 'South Sudan'): 1000,
    ('Central African Republic', 'Sudan'): 1500,
    ('Canada', 'United States'): 890,
    ('Canada', 'Greenland'): 3000,
    ('Switzerland', 'Austria'): 750,
    ('Switzerland', 'France'): 580,
    ('Switzerland', 'Germany'): 360,
    ('Switzerland', 'Italy'): 740,
    ('Switzerland', 'Liechtenstein'): 120,
    ('Liechtenstein', 'Austria'): 600,
    ('Liechtenstein', 'Switzerland'): 120,
    ('China', 'Afghanistan'): 5000,
    ('China', 'Bhutan'): 470,
    ('China', 'India'): 2000,
    ('China', 'Kazakhstan'): 1800,
    ('China', 'Kyrgyzstan'): 1200,
    ('China', 'Laos'): 1600,
    ('China', 'Mongolia'): 1300,
    ('China', 'Myanmar'): 1900,
    ('China', 'Nepal'): 1200,
    ('China', 'North Korea'): 1400,
    ('China', 'Pakistan'): 1500,
    ('China', 'Russian Federation'): 4200,
    ('China', 'Tajikistan'): 1000,
    ('China', 'Vietnam'): 1300,
    ("Côte d'Ivoire", 'Burkina Faso'): 610,
    ("Côte d'Ivoire", 'Ghana'): 370,
    ("Côte d'Ivoire", 'Guinea'): 820,
    ("Côte d'Ivoire", 'Liberia'): 720,
    ("Côte d'Ivoire", 'Mali'): 900,
    ('Cameroon', 'Central African Republic'): 800,
    ('Cameroon', 'Chad'): 1100,
    ('Cameroon', 'Republic of Congo'): 1200,
    ('Cameroon', 'Equatorial Guinea'): 450,
    ('Cameroon', 'Gabon'): 900,
    ('Cameroon', 'Nigeria'): 800,
    ('Democratic Republic of the Congo', 'Angola'): 400,
    ('Democratic Republic of the Congo', 'Burundi'): 200,
    ('Democratic Republic of the Congo', 'Central African Republic'): 1400,
    ('Democratic Republic of the Congo', 'Republic of Congo'): 1200,
    ('Democratic Republic of the Congo', 'Rwanda'): 120,
    ('Democratic Republic of the Congo', 'South Sudan'): 1500,
    ('Democratic Republic of the Congo', 'Tanzania'): 800,
    ('Democratic Republic of the Congo', 'Uganda'): 900,
    ('Democratic Republic of the Congo', 'Zambia'): 1050,
    ('Republic of Congo', 'Angola'): 250,
    ('Republic of Congo', 'Cameroon'): 1200,
    ('Republic of Congo', 'Central African Republic'): 1200,
    ('Republic of Congo', 'Democratic Republic of the Congo'): 1200,
    ('Republic of Congo', 'Gabon'): 800,
    ('Colombia', 'Brazil'): 2500,
    ('Colombia', 'Ecuador'): 720,
    ('Colombia', 'Panama'): 700,
    ('Colombia', 'Peru'): 1800,
    ('Colombia', 'Venezuela'): 1020,
    ('Costa Rica', 'Nicaragua'): 309,
    ('Costa Rica', 'Panama'): 348,
    ('Cuba', 'Jamaica'): 381,
    ('Cuba', 'United States'): 180,
    ('Cuba', 'Bahamas'): 150,
    ('Cuba', 'Mexico'): 210,
    ('Cuba', 'Haiti'): 770,
    ('Czech Republic', 'Austria'): 250,
    ('Czech Republic', 'Germany'): 350,
    ('Czech Republic', 'Poland'): 300,
    ('Czech Republic', 'Slovakia'): 200,
    ('Germany', 'Austria'): 680,
    ('Germany', 'Belgium'): 770,
    ('Germany', 'Czech Republic'): 350,
    ('Germany', 'Denmark'): 350,
    ('Germany', 'France'): 450,
    ('Germany', 'Luxembourg'): 190,
    ('Germany', 'Netherlands'): 210,
    ('Germany', 'Poland'): 460,
    ('Germany', 'Switzerland'): 360,
    ('Djibouti', 'Eritrea'): 113,
    ('Djibouti', 'Ethiopia'): 337,
    ('Djibouti', 'Somalia'): 400,
    ('Denmark', 'Germany'): 350,
    ('Dominican Republic', 'Haiti'): 390,
    ('Dominican Republic', 'Puerto Rico'): 380,
    ('Algeria', 'Libya'): 982,
    ('Algeria', 'Mali'): 1379,
    ('Algeria', 'Mauritania'): 1400,
    ('Algeria', 'Morocco'): 1050,
    ('Algeria', 'Niger'): 956,
    ('Algeria', 'Tunisia'): 965,
    ('Algeria', 'Western Sahara'): 2000,
    ('Ecuador', 'Colombia'): 720,
    ('Ecuador', 'Peru'): 1500,
    ('Egypt', 'Israel'): 430,
    ('Egypt', 'Libya'): 1115,
    ('Egypt', 'Sudan'): 1275,
    ('Eritrea', 'Djibouti'): 113,
    ('Eritrea', 'Ethiopia'): 1030,
    ('Eritrea', 'Sudan'): 800,
    ('Estonia', 'Latvia'): 267,
    ('Estonia', 'Russian Federation'): 860,
    ('Ethiopia', 'Djibouti'): 337,
    ('Ethiopia', 'Eritrea'): 1030,
    ('Ethiopia', 'Kenya'): 1230,
    ('Ethiopia', 'Somalia'): 1220,
    ('Ethiopia', 'South Sudan'): 1260,
    ('Ethiopia', 'Sudan'): 1440,
    ('Finland', 'Norway'): 720,
    ('Finland', 'Russian Federation'): 1340,
    ('Finland', 'Sweden'): 530,
    ('Gabon', 'Cameroon'): 900,
    ('Gabon', 'Republic of Congo'): 800,
    ('Gabon', 'Equatorial Guinea'): 450,
    ('United Kingdom', 'Ireland'): 470,
    ('United Kingdom', 'France'): 780,
    ('United Kingdom', 'Iceland'): 1900,
    ('United Kingdom', 'Falkland Islands'): 1400,
    ('Falkland Islands', 'Argentina'): 1400,
    ('France', 'United Kingdom'): 780,
    ('Georgia', 'Armenia'): 280,
    ('Georgia', 'Azerbaijan'): 450,
    ('Georgia', 'Russian Federation'): 900,
    ('Georgia', 'Turkey'): 620,
    ('Ghana', 'Burkina Faso'): 760,
    ('Ghana', "Côte d'Ivoire"): 370,
    ('Ghana', 'Togo'): 540,
    ('Guinea', "Côte d'Ivoire"): 820,
    ('Guinea', 'Guinea-Bissau'): 380,
    ('Guinea', 'Liberia'): 590,
    ('Guinea', 'Mali'): 850,
    ('Guinea', 'Senegal'): 330,
    ('Guinea', 'Sierra Leone'): 360,
    ('Gambia', 'Senegal'): 740,
    ('Gambia', 'Cape Verde'): 800,
    ('Guinea-Bissau', 'Guinea'): 380,
    ('Guinea-Bissau', 'Senegal'): 340,
    ('Equatorial Guinea', 'Cameroon'): 450,
    ('Equatorial Guinea', 'Gabon'): 300,
    ('Greece', 'Albania'): 262,
    ('Greece', 'Bulgaria'): 525,
    ('Greece', 'North Macedonia'): 230,
    ('Greece', 'Turkey'): 800,
    ('Greece', 'Cyprus'): 800,
    ('Guatemala', 'Belize'): 92,
    ('Guatemala', 'El Salvador'): 204,
    ('Guatemala', 'Honduras'): 256,
    ('Guatemala', 'Mexico'): 962,
    ('Guyana', 'Brazil'): 1600,
    ('Guyana', 'Suriname'): 600,
    ('Guyana', 'Venezuela'): 700,
    ('Honduras', 'El Salvador'): 256,
    ('El Salvador', 'Guatemala'): 204,
    ('El Salvador', 'Honduras'): 256,
    ('Honduras', 'Guatemala'): 256,
    ('Honduras', 'Nicaragua'): 358,
    ('Croatia', 'Bosnia and Herzegovina'): 400,
    ('Croatia', 'Hungary'): 305,
    ('Croatia', 'Montenegro'): 450,
    ('Croatia', 'Serbia'): 300,
    ('Croatia', 'Slovenia'): 140,
    ('Haiti', 'Dominican Republic'): 390,
    ('Haiti', 'Cuba'): 770,
    ('Haiti', 'Jamaica'): 540,
    ('Hungary', 'Austria'): 240,
    ('Hungary', 'Croatia'): 305,
    ('Hungary', 'Romania'): 600,
    ('Hungary', 'Serbia'): 370,
    ('Hungary', 'Slovakia'): 200,
    ('Hungary', 'Slovenia'): 460,
    ('Hungary', 'Ukraine'): 110,
    ('Indonesia', 'Malaysia'): 1200,
    ('Indonesia', 'Papua New Guinea'): 820,
    ('Indonesia', 'Timor-Leste'): 1250,
    ('Timor-Leste', 'Indonesia'): 1250,
    ('Indonesia', 'Australia'): 5220,
    ('India', 'Bangladesh'): 1420,
    ('India', 'Bhutan'): 180,
    ('India', 'China'): 2000,
    ('India', 'Myanmar'): 1463,
    ('India', 'Nepal'): 800,
    ('India', 'Pakistan'): 676,
    ('India', 'Sri Lanka'): 30,
    ('India', 'Maldives'): 500,
    ('Ireland', 'United Kingdom'): 470,
    ('Iran', 'Afghanistan'): 921,
    ('Iran', 'Armenia'): 790,
    ('Iran', 'Azerbaijan'): 530,
    ('Iran', 'Iraq'): 1450,
    ('Iran', 'Pakistan'): 909,
    ('Iran', 'Turkey'): 2000,
    ('Iran', 'Turkmenistan'): 1200,
    ('Iraq', 'Iran'): 1450,
    ('Iraq', 'Jordan'): 800,
    ('Iraq', 'Kuwait'): 200,
    ('Iraq', 'Saudi Arabia'): 814,
    ('Iraq', 'Syria'): 605,
    ('Iraq', 'Turkey'): 1200,
    ('Iceland', 'Greenland'): 3000,
    ('Greenland', 'Iceland'): 3000,
    ('Greenland', 'Canada'): 3000,
    ('Iceland', 'United Kingdom'): 1900,
    ('Israel', 'Egypt'): 430,
    ('Israel', 'Jordan'): 100,
    ('Israel', 'Lebanon'): 79,
    ('Israel', 'Syria'): 83,
    ('Italy', 'Austria'): 1130,
    ('Italy', 'France'): 960,
    ('Italy', 'San Marino'): 23,
    ('San Marino', 'Italy'): 23,
    ('Italy', 'Slovenia'): 230,
    ('Italy', 'Switzerland'): 740,
    ('Italy', 'Vatican City'): 2,
    ('Vatican City', 'Italy'): 2,
    ('Italy', 'Malta'): 1000,
    ('Jamaica', 'Cuba'): 381,
    ('Jamaica', 'Haiti'): 540,
    ('Jordan', 'Iraq'): 800,
    ('Jordan', 'Israel'): 100,
    ('Jordan', 'Saudi Arabia'): 730,
    ('Jordan', 'Syria'): 360,
    ('Japan', 'South Korea'): 1200,
    ('Japan', 'Russian Federation'): 1500,
    ('Japan', 'Federated States of Micronesia'): 3000,
    ('Federated States of Micronesia', 'Japan'): 3000,
    ('Russian Federation', 'Japan'): 1500,
    ('Kazakhstan', 'China'): 1800,
    ('Kazakhstan', 'Kyrgyzstan'): 1200,
    ('Kazakhstan', 'Russian Federation'): 2500,
    ('Kazakhstan', 'Turkmenistan'): 1700,
    ('Turkmenistan', 'Afghanistan'): 744,
    ('Turkmenistan', 'Iran'): 1200,
    ('Turkmenistan', 'Kazakhstan'): 1700,
    ('Kazakhstan', 'Uzbekistan'): 1400,
    ('Kenya', 'Ethiopia'): 1230,
    ('Kenya', 'Somalia'): 682,
    ('Kenya', 'South Sudan'): 930,
    ('Kenya', 'Tanzania'): 775,
    ('Kenya', 'Uganda'): 665,
    ('Kyrgyzstan', 'China'): 1200,
    ('Kyrgyzstan', 'Kazakhstan'): 1200,
    ('Kyrgyzstan', 'Tajikistan'): 870,
    ('Kyrgyzstan', 'Uzbekistan'): 680,
    ('Cambodia', 'Laos'): 540,
    ('Cambodia', 'Thailand'): 800,
    ('Cambodia', 'Vietnam'): 650,
    ('South Korea', 'North Korea'): 250,
    ('South Korea', 'Japan'): 1200,
    ('North Korea', 'China'): 1400,
    ('North Korea', 'South Korea'): 250,
    ('North Korea', 'Russian Federation'): 1500,
    ('Kuwait', 'Iraq'): 200,
    ('Kuwait', 'Saudi Arabia'): 614,
    ('Laos', 'Cambodia'): 540,
    ('Laos', 'China'): 1600,
    ('Laos', 'Myanmar'): 235,
    ('Laos', 'Thailand'): 480,
    ('Laos', 'Vietnam'): 490,
    ('Vietnam', 'Cambodia'): 650,
    ('Vietnam', 'China'): 1300,
    ('Vietnam', 'Laos'): 490,
    ('Lebanon', 'Israel'): 79,
    ('Lebanon', 'Syria'): 83,
    ('Liberia', "Côte d'Ivoire"): 720,
    ('Liberia', 'Guinea'): 590,
    ('Liberia', 'Sierra Leone'): 360,
    ('Libya', 'Algeria'): 982,
    ('Libya', 'Chad'): 1050,
    ('Libya', 'Egypt'): 1115,
    ('Libya', 'Niger'): 956,
    ('Libya', 'Sudan'): 1275,
    ('Libya', 'Tunisia'): 459,
    ('Tunisia', 'Algeria'): 965,
    ('Tunisia', 'Libya'): 459,
    ('Sri Lanka', 'India'): 30,
    ('Lesotho', 'South Africa'): 10,  # Totalmente rodeado
    ('Lithuania', 'Belarus'): 180,
    ('Lithuania', 'Latvia'): 267,
    ('Lithuania', 'Poland'): 300,
    ('Lithuania', 'Russian Federation'): 860,
    ('Luxembourg', 'Belgium'): 190,
    ('Luxembourg', 'France'): 290,
    ('Luxembourg', 'Germany'): 190,
    ('Latvia', 'Belarus'): 170,
    ('Latvia', 'Estonia'): 267,
    ('Latvia', 'Lithuania'): 267,
    ('Latvia', 'Russian Federation'): 860,
    ('Morocco', 'Algeria'): 1050,
    ('Morocco', 'Western Sahara'): 445,
    ('Morocco', 'Spain'): 13,
    ('Moldova', 'Romania'): 470,
    ('Moldova', 'Ukraine'): 420,
    ('Madagascar', 'Mozambique'): 400,
    ('Mexico', 'Belize'): 277,
    ('Mexico', 'Guatemala'): 962,
    ('Mexico', 'United States'): 3200,
    ('Mexico', 'Cuba'): 3200,
    ('North Macedonia', 'Albania'): 151,
    ('North Macedonia', 'Bulgaria'): 239,
    ('North Macedonia', 'Greece'): 230,
    ('North Macedonia', 'Kosovo'): 90,
    ('North Macedonia', 'Serbia'): 430,
    ('Mali', 'Algeria'): 1379,
    ('Mali', 'Burkina Faso'): 920,
    ('Mali', 'Guinea'): 850,
    ('Mali', "Côte d'Ivoire"): 900,
    ('Mali', 'Mauritania'): 860,
    ('Mali', 'Niger'): 821,
    ('Mali', 'Senegal'): 640,
    ('Myanmar', 'Bangladesh'): 271,
    ('Myanmar', 'China'): 1900,
    ('Myanmar', 'India'): 1463,
    ('Myanmar', 'Laos'): 235,
    ('Myanmar', 'Thailand'): 580,
    ('Montenegro', 'Albania'): 160,
    ('Montenegro', 'Bosnia and Herzegovina'): 230,
    ('Montenegro', 'Croatia'): 450,
    ('Montenegro', 'Kosovo'): 80,
    ('Montenegro', 'Serbia'): 200,
    ('Mongolia', 'China'): 1300,
    ('Mongolia', 'Russian Federation'): 2100,
    ('Mozambique', 'Eswatini'): 200,
    ('Mozambique', 'Malawi'): 840,
    ('Mozambique', 'South Africa'): 490,
    ('Mozambique', 'Tanzania'): 750,
    ('Mozambique', 'Zambia'): 1400,
    ('Mozambique', 'Zimbabwe'): 800,
    ('Mozambique', 'Madagascar'): 400,
    ('Mozambique', 'Comoros'): 400,
    ('Mauritania', 'Algeria'): 1400,
    ('Mauritania', 'Mali'): 860,
    ('Mauritania', 'Senegal'): 500,
    ('Mauritania', 'Western Sahara'): 600,
    ('Western Sahara', 'Algeria'): 2000,
    ('Western Sahara', 'Morocco'): 445,
    ('Western Sahara', 'Mauritania'): 600,
    ('Malawi', 'Mozambique'): 840,
    ('Malawi', 'Tanzania'): 750,
    ('Malawi', 'Zambia'): 300,
    ('Namibia', 'Angola'): 1376,
    ('Namibia', 'Botswana'): 1100,
    ('Namibia', 'South Africa'): 960,
    ('Namibia', 'Zambia'): 700,
    ('Netherlands', 'Belgium'): 210,
    ('Niger', 'Algeria'): 956,
    ('Niger', 'Benin'): 420,
    ('Niger', 'Burkina Faso'): 420,
    ('Niger', 'Chad'): 1200,
    ('Niger', 'Libya'): 956,
    ('Niger', 'Mali'): 821,
    ('Niger', 'Nigeria'): 1500,
    ('Nigeria', 'Benin'): 700,
    ('Nigeria', 'Cameroon'): 800,
    ('Nigeria', 'Chad'): 1200,
    ('Nigeria', 'Niger'): 1500,
    ('Nicaragua', 'Costa Rica'): 309,
    ('Nicaragua', 'Honduras'): 358,
    ('Norway', 'Finland'): 720,
    ('Norway', 'Russian Federation'): 1340,
    ('Norway', 'Sweden'): 530,
    ('Sweden', 'Denmark'): 530,
    ('Sweden', 'Finland'): 530,
    ('Sweden', 'Norway'): 720,
    ('Nepal', 'China'): 1200,
    ('Nepal', 'India'): 800,
    ('Oman', 'Saudi Arabia'): 900,
    ('Oman', 'United Arab Emirates'): 450,
    ('Oman', 'Yemen'): 750,
    ('Pakistan', 'Afghanistan'): 560,
    ('Pakistan', 'China'): 1500,
    ('Pakistan', 'India'): 676,
    ('Pakistan', 'Iran'): 909,
    ('Panama', 'Colombia'): 700,
    ('Panama', 'Costa Rica'): 348,
    ('Peru', 'Bolivia'): 1070,
    ('Peru', 'Brazil'): 2600,
    ('Peru', 'Chile'): 1500,
    ('Peru', 'Colombia'): 1800,
    ('Peru', 'Ecuador'): 1500,
    ('Philippines', 'Brunei Darussalam'): 1200,
    ('Philippines', 'China'): 1300,
    ('Philippines', 'Indonesia'): 820,
    ('Philippines', 'Malaysia'): 160,
    ('Philippines', 'Taiwan'): 300,
    ('Papua New Guinea', 'Indonesia'): 820,
    ('Papua New Guinea', 'Australia'): 3360,
    ('Poland', 'Belarus'): 250,
    ('Poland', 'Czech Republic'): 300,
    ('Poland', 'Germany'): 460,
    ('Poland', 'Lithuania'): 300,
    ('Poland', 'Russian Federation'): 860,
    ('Poland', 'Slovakia'): 200,
    ('Poland', 'Ukraine'): 470,
    ('Portugal', 'Spain'): 623,
    ('Paraguay', 'Argentina'): 1300,
    ('Paraguay', 'Bolivia'): 850,
    ('Paraguay', 'Brazil'): 1300,
    ('Qatar', 'Saudi Arabia'): 87,
    ('Romania', 'Bulgaria'): 360,
    ('Romania', 'Hungary'): 600,
    ('Romania', 'Moldova'): 470,
    ('Romania', 'Serbia'): 530,
    ('Romania', 'Ukraine'): 600,
    ('Rwanda', 'Burundi'): 120,
    ('Rwanda', 'Democratic Republic of the Congo'): 120,
    ('Rwanda', 'Tanzania'): 800,
    ('Rwanda', 'Uganda'): 510,
    ('Saudi Arabia', 'Iraq'): 814,
    ('Saudi Arabia', 'Jordan'): 730,
    ('Saudi Arabia', 'Kuwait'): 614,
    ('Saudi Arabia', 'Oman'): 900,
    ('Saudi Arabia', 'Qatar'): 87,
    ('Saudi Arabia', 'United Arab Emirates'): 900,
    ('Saudi Arabia', 'Yemen'): 1300,
    ('Yemen', 'Oman'): 750,
    ('Oman', 'Saudi Arabia'): 900,
    ('Oman', 'United Arab Emirates'): 450,
    ('Oman', 'Yemen'): 750,
    ('Yemen', 'Saudi Arabia'): 1300,
    ('Sudan', 'Central African Republic'): 1500,
    ('Sudan', 'Chad'): 1100,
    ('Sudan', 'Egypt'): 1275,
    ('Sudan', 'Eritrea'): 800,
    ('Sudan', 'Ethiopia'): 1440,
    ('Sudan', 'Libya'): 1275,
    ('Sudan', 'South Sudan'): 700,
    ('Senegal', 'Gambia'): 740,
    ('Senegal', 'Guinea'): 330,
    ('Senegal', 'Guinea-Bissau'): 340,
    ('Senegal', 'Mali'): 640,
    ('Senegal', 'Mauritania'): 500,
    ('Singapore', 'Malaysia'): 350,
    ('Singapore', 'Indonesia'): 30,
    ('Sierra Leone', 'Guinea'): 360,
    ('Sierra Leone', 'Liberia'): 360,
    ('Slovakia', 'Austria'): 80,
    ('Slovakia', 'Czech Republic'): 200,
    ('Slovakia', 'Hungary'): 200,
    ('Slovakia', 'Poland'): 300,
    ('Slovakia', 'Ukraine'): 470,
    ('Slovenia', 'Austria'): 380,
    ('Slovenia', 'Croatia'): 140,
    ('Slovenia', 'Hungary'): 460,
    ('Slovenia', 'Italy'): 230,
    ('Somalia', 'Djibouti'): 400,
    ('Somalia', 'Ethiopia'): 1220,
    ('Somalia', 'Kenya'): 682,
    ('South Africa', 'Botswana'): 960,
    ('South Africa', 'Eswatini'): 200,
    ('South Africa', 'Lesotho'): 10,
    ('South Africa', 'Mozambique'): 490,
    ('South Africa', 'Namibia'): 960,
    ('South Africa', 'Zimbabwe'): 840,
    ('South Sudan', 'Central African Republic'): 1000,
    ('South Sudan', 'Democratic Republic of the Congo'): 1500,
    ('South Sudan', 'Ethiopia'): 1260,
    ('South Sudan', 'Kenya'): 930,
    ('South Sudan', 'Sudan'): 700,
    ('South Sudan', 'Uganda'): 510,
    ('Uganda', 'Burundi'): 120,
    ('Uganda', 'Democratic Republic of the Congo'): 900,
    ('Uganda', 'Kenya'): 665,
    ('Uganda', 'Rwanda'): 510,
    ('Uganda', 'South Sudan'): 510,
    ('Uganda', 'Tanzania'): 800,
    ('Serbia', 'Bosnia and Herzegovina'): 290,
    ('Serbia', 'Bulgaria'): 400,
    ('Serbia', 'Croatia'): 300,
    ('Serbia', 'Hungary'): 370,
    ('Serbia', 'Kosovo'): 90,
    ('Serbia', 'Montenegro'): 200,
    ('Serbia', 'North Macedonia'): 430,
    ('Serbia', 'Romania'): 530,
    ('Suriname', 'Brazil'): 2000,
    ('Suriname', 'French Guiana'): 500,
    ('Suriname', 'Guyana'): 600,
    ('Syria', 'Iraq'): 605,
    ('Syria', 'Israel'): 83,
    ('Syria', 'Jordan'): 360,
    ('Syria', 'Lebanon'): 83,
    ('Syria', 'Turkey'): 800,
    ('Eswatini', 'Mozambique'): 200,
    ('Eswatini', 'South Africa'): 200,
    ('Chad', 'Cameroon'): 1100,
    ('Chad', 'Central African Republic'): 1100,
    ('Chad', 'Libya'): 1050,
    ('Chad', 'Niger'): 1200,
    ('Chad', 'Sudan'): 1100,
    ('Chad', 'Nigeria'): 1200,
    ('Togo', 'Benin'): 870,
    ('Benin', 'Burkina Faso'): 420,
    ('Benin', 'Niger'): 420,
    ('Benin', 'Nigeria'): 700,
    ('Benin', 'Togo'): 870,
    ('Togo', 'Burkina Faso'): 870,
    ('Togo', 'Ghana'): 540,
    ('Thailand', 'Cambodia'): 800,
    ('Thailand', 'Laos'): 480,
    ('Thailand', 'Malaysia'): 1220,
    ('Thailand', 'Myanmar'): 580,
    ('Tajikistan', 'Afghanistan'): 120,
    ('Tajikistan', 'China'): 1000,
    ('Tajikistan', 'Kyrgyzstan'): 870,
    ('Tajikistan', 'Uzbekistan'): 680,
    ('Uzbekistan', 'Afghanistan'): 137,
    ('Uzbekistan', 'Kazakhstan'): 1400,
    ('Uzbekistan', 'Kyrgyzstan'): 680,
    ('Uzbekistan', 'Tajikistan'): 680,
    ('Somalia', 'Djibouti'): 400,
    ('Somalia', 'Ethiopia'): 1220,
    ('Somalia', 'Kenya'): 682,
    ('Kosovo', 'Albania'): 90,
    ('Albania', 'Montenegro'): 160,
    ('Albania', 'North Macedonia'): 151,
    ('Albania', 'Greece'): 262,
    ('Albania', 'Kosovo'): 90,
    ('Kosovo', 'Montenegro'): 80,
    ('Kosovo', 'North Macedonia'): 90,
    ('Kosovo', 'Serbia'): 90,
    ('South Africa', 'Namibia'): 960,
    ('South Africa', 'Botswana'): 960,
    ('South Africa', 'Zimbabwe'): 840,
    ('Zimbabwe', 'Botswana'): 840,
    ('Zimbabwe', 'Mozambique'): 800,
    ('Zimbabwe', 'South Africa'): 840,
    ('Zimbabwe', 'Zambia'): 500,
    ('Zambia', 'Angola'): 400,
    ('Zambia', 'Botswana'): 700,
    ('Zambia', 'Democratic Republic of the Congo'): 1050,
    ('Zambia', 'Malawi'): 300,
    ('Zambia', 'Mozambique'): 1400,
    ('Zambia', 'Namibia'): 700,
    ('Zambia', 'Tanzania'): 750,
    ('Zambia', 'Zimbabwe'): 500,
    ('Tanzania', 'Zambia'): 750,
    ('South Africa', 'Mozambique'): 490,
    ('New Zealand', 'Australia'): 2320,
    ('Chile', 'Argentina'): 1400,
    ('Chile', 'Bolivia'): 1200,
    ('Chile', 'Peru'): 1500,
    ('Netherlands', 'Germany'): 350,
    ('Portugal', 'Spain'): 623,
    ('Russian Federation', 'Norway'): 196,
    ('Russian Federation', 'Finland'): 1340,
    ('Russian Federation', 'Estonia'): 860,
    ('Russian Federation', 'Latvia'): 860,
    ('Russian Federation', 'Lithuania'): 860,
    ('Russian Federation', 'Poland'): 860,
    ('Russian Federation', 'Belarus'): 700,
    ('Russian Federation', 'Ukraine'): 530,
    ('Russian Federation', 'Georgia'): 900,
    ('Russian Federation', 'Azerbaijan'): 2500,
    ('Russian Federation', 'Kazakhstan'): 2500,
    ('Russian Federation', 'China'): 4200,
    ('Russian Federation', 'Mongolia'): 2100,
    ('Russian Federation', 'North Korea'): 17,
    ('Russian Federation', 'United States'): 7000,
    ('Ukraine', 'Belarus'): 700,
    ('Ukraine', 'Hungary'): 110,
    ('Ukraine', 'Moldova'): 420,
    ('Ukraine', 'Poland'): 470,
    ('Ukraine', 'Romania'): 600,
    ('Ukraine', 'Slovakia'): 470,
    ('Ukraine', 'Russian Federation'): 530,
    ('Spain', 'France'): 623,
    ('Spain', 'Portugal'): 623,
    ('Spain', 'Andorra'): 85,
    ('France', 'Andorra'): 85,
    ('Spain', 'Morocco'): 13,
    ('France', 'Belgium'): 320,
    ('France', 'Luxembourg'): 290,
    ('France', 'Germany'): 450,
    ('France', 'Switzerland'): 580,
    ('France', 'Monaco'): 13,
    ('Andorra', 'France'): 85,
    ('Andorra', 'Spain'): 85,
    ('Monaco', 'France'): 13,
    ('France', 'Italy'): 960,
    ('France', 'Spain'): 623,
    ('United States', 'Canada'): 890,
    ('United States', 'Mexico'): 3200,
    ('United States', 'Russian Federation'): 7000,
    ('United States', 'Bahamas'): 180,
    ('United States', 'Cuba'): 180,
    ('United States', 'Bermuda'): 1030,
    ('French Guiana', 'Brazil'): 500,
    ('French Guiana', 'Suriname'): 500,
    ('Aruba', 'Netherlands Antilles'): 130,
    ('Netherlands Antilles', 'Aruba'): 130,
    ('Anguilla', 'Saint Kitts and Nevis'): 100,
    ('Anguilla', 'Saint Barthélemy'): 50,
    ('Saint Barthélemy', 'Anguilla'): 50,
    ('American Samoa', 'Samoa'): 150,
    ('Samoa', 'American Samoa'): 150,
    ('Antigua and Barbuda', 'Saint Kitts and Nevis'): 80,
    ('Antigua and Barbuda', 'Montserrat'): 50,
    ('Bahrain', 'Saudi Arabia'): 25,
    ('Saudi Arabia', 'Bahrain'): 25,
    ('Bahamas', 'Cuba'): 150,
    ('Bahamas', 'United States'): 180,
    ('Saint-Barthélemy', 'Saint Martin'): 15,
    ('Saint-Barthélemy', 'Saint Kitts and Nevis'): 50,
    ('Saint Kitts and Nevis', 'Saint-Barthélemy'): 50,
    ('Saint Martin', 'Saint-Barthélemy'): 15,
    ('Saint Martin', 'Saint Kitts and Nevis'): 50,
    ('Saint Kitts and Nevis', 'Saint Martin'): 50,
    ('Bermuda', 'United States'): 1030,
    ('Barbados', 'Saint Lucia'): 174,
    ('Barbados', 'Saint Vincent and the Grenadines'): 190,
    ('Comoros', 'Mozambique'): 400,
    ('Comoros', 'Tanzania'): 750,
    ('Tanzania', 'Kenya'): 775,
    ('Tanzania', 'Malawi'): 750,
    ('Tanzania', 'Mozambique'): 750,
    ('Tanzania', 'Rwanda'): 800,
    ('Tanzania', 'Uganda'): 510,
    ('Tanzania', 'Democratic Republic of the Congo'): 900,
    ('Tanzania', 'Comoros'): 750,
    ('Tanzania', 'Burundi'): 120,
    ('Cape Verde', 'Senegal'): 640,
    ('Cape Verde', 'Gambia'): 800,
    ('Senegal', 'Cape Verde'): 640,
    ('Curaçao', 'Aruba'): 130,
    ('Aruba', 'Curaçao'): 130,
    ('Curaçao', 'Venezuela'): 80,
    ('Venezuela', 'Colombia'): 1800,
    ('Venezuela', 'Guyana'): 700,
    ('Venezuela', 'Brazil'): 2000,
    ('Venezuela', 'Curaçao'): 80,
    ('Cayman Islands', 'Cuba'): 240,
    ('Cuba', 'Cayman Islands'): 240,
    ('Cayman Islands', 'Jamaica'): 300,
    ('Jamaica', 'Cayman Islands'): 300,
    ('Cyprus', 'Greece'): 1120,
    ('Cyprus', 'Turkey'): 800,
    ('Turkey', 'Greece'): 800,
    ('Turkey', 'Armenia'): 790,
    ('Turkey', 'Azerbaijan'): 530,
    ('Turkey', 'Georgia'): 620,
    ('Turkey', 'Iran'): 2000,
    ('Turkey', 'Iraq'): 1200,
    ('Turkey', 'Syria'): 800,
    ('Turkey', 'Bulgaria'): 530,
    ('Turkey', 'Cyprus'): 800,
    ('Dominica', 'Saint Kitts and Nevis'): 200,
    ('Saint Kitts and Nevis', 'Dominica'): 200,
    ('Dominica', 'Martinique'): 190,
    ('Martinique', 'Dominica'): 190,
    ('Saint Kitts and Nevis', 'Saint Lucia'): 250,
    ('Martinique', 'Dominica'): 190,
    ('Falkland Islands', 'United Kingdom'): 12700,
    ('Faeroe Islands', 'Denmark'): 1300,
    ('Denmark', 'Faeroe Islands'): 1300,
    ('Denmark', 'Sweden'): 530,
    ('Federated States of Micronesia', 'Guam'): 1600,
    ('Federated States of Micronesia', 'Marshall Islands'): 1500,
    ('Federated States of Micronesia', 'Northern Mariana Islands'): 1800,
    ('Federated States of Micronesia', 'Palau'): 1200,
    ('Federated States of Micronesia', 'Nauru'): 1400,
    ('Grenada', 'Saint Vincent and the Grenadines'): 150,
    ('Grenada', 'Saint Lucia'): 200,
    ('Guam', 'Federated States of Micronesia'): 1600,
    ('Saint Kitts and Nevis', 'Saint Lucia'): 300,
    ('Saint Kitts and Nevis', 'Antigua and Barbuda'): 80,
    ('Saint Lucia', 'Saint Vincent and the Grenadines'): 150,
    ('Saint Lucia', 'Barbados'): 174,
    ('Saint Lucia', 'Saint Kitts and Nevis'): 300,
    ('Maldives', 'India'): 700,
    ('Marshall Islands', 'Federated States of Micronesia'): 1500,
    ('Malta', 'Italy'): 80,
    ('Northern Mariana Islands', 'Federated States of Micronesia'): 1800,
    ('Montserrat', 'Saint Kitts and Nevis'): 50,
    ('Saint Kitts and Nevis', 'Antigua and Barbuda'): 80,
    ('Saint Kitts and Nevis', 'Montserrat'): 50,
    ('Saint Kitts and Nevis', 'Anguilla'): 100,
    ('Montserrat', 'Antigua and Barbuda'): 50,
    ('Mauritius', 'Réunion'): 200,
    ('Réunion', 'Mauritius'): 200,
    ('Réunion', 'Mayotte'): 200,
    ('Mayotte', 'Réunion'): 200,
    ('Réunion', 'Madagascar'): 400,
    ('Madagascar', 'Réunion'): 400,
    ('New Caledonia', 'Australia'): 1500,
    ('Australia', 'New Caledonia'): 1500,
    ('Nauru', 'Federated States of Micronesia'): 1400,
    ('Palau', 'Federated States of Micronesia'): 1200,
    ('Puerto Rico', 'Dominican Republic'): 380,
    ('Malaysia', 'Singapore'): 350,
    ('Indonesia', 'Singapore'): 30,
    ('Malaysia', 'Brunei Darussalam'): 1200,
    ('Malaysia', 'Thailand'): 1220,
    ('Malaysia', 'Indonesia'): 1200,
    ('Malaysia', 'Philippines'): 160,
    ('Saint Vincent and the Grenadines', 'Saint Lucia'): 150,
    ('Saint Vincent and the Grenadines', 'Barbados'): 190,
    ('Saint Vincent and the Grenadines', 'Grenada'): 150,
    ('Indonesia', 'Philippines'): 1200,
    ('China', 'Philippines'): 1300,
    ('Taiwan', 'Philippines'): 300,
    ('Saint Lucia', 'Grenada'): 150,
    ('Palestine', 'Israel'): 100,
    ('Israel', 'Palestine'): 100,
    ('Palestine', 'Jordan'): 100,
    ('Jordan', 'Palestine'): 100,
    ('Palestine', 'Egypt'): 430,
    ('Egypt', 'Palestine'): 430,
    ('Swaziland', 'South Africa'): 200,
    ('Swaziland', 'Mozambique'): 200,
    ('South Africa', 'Swaziland'): 200,
    ('Mozambique', 'Swaziland'): 200,
}
